"""make scoring fields nullable until step 5

Revision ID: 01ae6af82c6a
Revises: a526950ba86e
Create Date: 2026-09-13 16:48:52.585789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ae6af82c6a'
down_revision: Union[str, Sequence[str], None] = 'a526950ba86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logged_sets', 'estimated_1rm_kg',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=True)
    op.alter_column('logged_sets', 'relative_ratio',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True)
    op.alter_column('logged_sets', 'points',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logged_sets', 'points',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False)
    op.alter_column('logged_sets', 'relative_ratio',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False)
    op.alter_column('logged_sets', 'estimated_1rm_kg',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=False)
    # ### end Alembic commands ###
