"""initial schema

Revision ID: a526950ba86e
Revises: 
Create Date: 2026-09-13 14:06:12.908119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a526950ba86e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('weighted', 'bodyweight', name='exercise_type'), nullable=False),
    sa.Column('muscle_group', sa.Enum('push', 'pull', 'legs', 'core', 'full_body', name='muscle_group'), nullable=False),
    sa.Column('weight_coefficient', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('weekly_eligible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gyms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('join_code', sa.String(), nullable=False),
    sa.Column('brand_color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_table('tier_thresholds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('min_points', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('bronze', 'silver', 'gold', 'platinum', 'diamond', 'olympian', name='tier'), nullable=False),
    sa.Column('sub_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=False),
    sa.Column('bodyweight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('logged_sets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('added_weight_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('bodyweight_at_log_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('estimated_1rm_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('relative_ratio', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_request_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_request_id')
    )
    op.create_index(op.f('ix_logged_sets_exercise_id'), 'logged_sets', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_logged_sets_gym_id'), 'logged_sets', ['gym_id'], unique=False)
    op.create_index(op.f('ix_logged_sets_user_id'), 'logged_sets', ['user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('member', 'admin', name='membership_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gym_id', name='uq_membership_user_gym')
    )
    op.create_index(op.f('ix_memberships_gym_id'), 'memberships', ['gym_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('weekly_exercise_bests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('estimated_1rm_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'exercise_id', 'user_id', 'week_start', name='uq_weekly_best_scope')
    )
    op.create_index(op.f('ix_weekly_exercise_bests_exercise_id'), 'weekly_exercise_bests', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_weekly_exercise_bests_gym_id'), 'weekly_exercise_bests', ['gym_id'], unique=False)
    op.create_index(op.f('ix_weekly_exercise_bests_user_id'), 'weekly_exercise_bests', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_exercise_bests_week_start'), 'weekly_exercise_bests', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_exercise_bests_week_start'), table_name='weekly_exercise_bests')
    op.drop_index(op.f('ix_weekly_exercise_bests_user_id'), table_name='weekly_exercise_bests')
    op.drop_index(op.f('ix_weekly_exercise_bests_gym_id'), table_name='weekly_exercise_bests')
    op.drop_index(op.f('ix_weekly_exercise_bests_exercise_id'), table_name='weekly_exercise_bests')
    op.drop_table('weekly_exercise_bests')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_gym_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_logged_sets_user_id'), table_name='logged_sets')
    op.drop_index(op.f('ix_logged_sets_gym_id'), table_name='logged_sets')
    op.drop_index(op.f('ix_logged_sets_exercise_id'), table_name='logged_sets')
    op.drop_table('logged_sets')
    op.drop_table('users')
    op.drop_table('tier_thresholds')
    op.drop_table('gyms')
    op.drop_table('exercises')
    # ### end Alembic commands ###
