/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["get_my_profile_users_me_get"];
        put?: never;
        /** Create My Profile */
        post: operations["create_my_profile_users_me_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Profile */
        patch: operations["update_my_profile_users_me_patch"];
        trace?: never;
    };
    "/users/{user_id}/tier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Tier */
        get: operations["get_user_tier_users__user_id__tier_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Gym */
        post: operations["create_gym_gyms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gym_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gym */
        get: operations["get_gym_gyms__gym_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gym_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_gyms__gym_id__leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gym_id}/exercises/{exercise_id}/weekly-leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weekly Leaderboard */
        get: operations["get_weekly_leaderboard_gyms__gym_id__exercises__exercise_id__weekly_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memberships/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Gym */
        post: operations["join_gym_memberships_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memberships/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Memberships */
        get: operations["list_my_memberships_memberships_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logged-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Logged Set */
        post: operations["create_logged_set_logged_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logged-sets/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Logged Sets Bulk */
        post: operations["create_logged_sets_bulk_logged_sets_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logged-sets/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Logged Sets */
        get: operations["list_my_logged_sets_logged_sets_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ExerciseOut */
        ExerciseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            type: components["schemas"]["ExerciseType"];
            muscle_group: components["schemas"]["MuscleGroup"];
            /** Weight Coefficient */
            weight_coefficient: number;
            /** Weekly Eligible */
            weekly_eligible: boolean;
        };
        /**
         * ExerciseType
         * @enum {string}
         */
        ExerciseType: "weighted" | "bodyweight";
        /** GymCreate */
        GymCreate: {
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Brand Color */
            brand_color?: string | null;
        };
        /** GymCreatedOut */
        GymCreatedOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Brand Color */
            brand_color: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Join Code */
            join_code: string;
        };
        /** GymLeaderboardEntry */
        GymLeaderboardEntry: {
            /** Rank */
            rank: number;
            /** Percentile */
            percentile: number;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Username */
            username: string;
            /** Bar Total */
            bar_total: number;
        };
        /**
         * GymOut
         * @description Public shape - deliberately excludes join_code so it can't be looked up
         *     by anyone who merely knows/guesses a gym's id; it's only handed back once,
         *     at creation, via GymCreatedOut.
         */
        GymOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Brand Color */
            brand_color: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoggedSetBulkCreate */
        LoggedSetBulkCreate: {
            /** Items */
            items: components["schemas"]["LoggedSetCreate"][];
        };
        /** LoggedSetCreate */
        LoggedSetCreate: {
            /**
             * Gym Id
             * Format: uuid
             */
            gym_id: string;
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Weight Kg */
            weight_kg: number;
            /** Reps */
            reps: number;
            /** Added Weight Kg */
            added_weight_kg?: number | null;
            /**
             * Client Request Id
             * Format: uuid
             */
            client_request_id: string;
        };
        /** LoggedSetOut */
        LoggedSetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Gym Id
             * Format: uuid
             */
            gym_id: string;
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Weight Kg */
            weight_kg: number;
            /** Reps */
            reps: number;
            /** Added Weight Kg */
            added_weight_kg: number | null;
            /** Bodyweight At Log Kg */
            bodyweight_at_log_kg: number;
            /** Estimated 1Rm Kg */
            estimated_1rm_kg: number | null;
            /** Relative Ratio */
            relative_ratio: number | null;
            /** Points */
            points: number | null;
            /** Verified */
            verified: boolean;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /**
             * Client Request Id
             * Format: uuid
             */
            client_request_id: string;
        };
        /** MembershipJoinRequest */
        MembershipJoinRequest: {
            /** Join Code */
            join_code: string;
        };
        /** MembershipOut */
        MembershipOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Gym Id
             * Format: uuid
             */
            gym_id: string;
            role: components["schemas"]["MembershipRole"];
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /**
         * MembershipRole
         * @enum {string}
         */
        MembershipRole: "member" | "admin";
        /**
         * MuscleGroup
         * @enum {string}
         */
        MuscleGroup: "push" | "pull" | "legs" | "core" | "full_body";
        /**
         * Sex
         * @enum {string}
         */
        Sex: "male" | "female";
        /**
         * Tier
         * @enum {string}
         */
        Tier: "bronze" | "silver" | "gold" | "platinum" | "diamond" | "olympian";
        /** TierOut */
        TierOut: {
            /** Bar Total */
            bar_total: number;
            tier: components["schemas"]["Tier"];
            /** Sub Level */
            sub_level: number;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            sex: components["schemas"]["Sex"];
            /** Bodyweight Kg */
            bodyweight_kg: number;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Email */
            email: string;
            sex: components["schemas"]["Sex"];
            /** Bodyweight Kg */
            bodyweight_kg: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Username */
            username?: string | null;
            /** Bodyweight Kg */
            bodyweight_kg?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklyLeaderboardEntry */
        WeeklyLeaderboardEntry: {
            /** Rank */
            rank: number;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Username */
            username: string;
            /** Weight Kg */
            weight_kg: number;
            /** Estimated 1Rm Kg */
            estimated_1rm_kg: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_my_profile_users_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_my_profile_users_me_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_my_profile_users_me_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_tier_users__user_id__tier_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_gym_gyms_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GymCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymCreatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gym_gyms__gym_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_gyms__gym_id__leaderboard_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymLeaderboardEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_leaderboard_gyms__gym_id__exercises__exercise_id__weekly_leaderboard_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path: {
                gym_id: string;
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyLeaderboardEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_gym_memberships_join_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipJoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_memberships_memberships_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_exercises_get: {
        parameters: {
            query?: {
                muscle_group?: components["schemas"]["MuscleGroup"] | null;
            };
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_logged_set_logged_sets_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoggedSetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_logged_sets_bulk_logged_sets_bulk_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoggedSetBulkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedSetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_logged_sets_logged_sets_me_get: {
        parameters: {
            query?: {
                gym_id?: string | null;
                exercise_id?: string | null;
            };
            header?: {
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedSetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
